# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(700, 551)
        self.gridLayout_6 = QtWidgets.QGridLayout(widget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.title_1 = QtWidgets.QLabel(widget)
        self.title_1.setObjectName("title_1")
        self.gridLayout_4.addWidget(self.title_1, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.a_lbl = QtWidgets.QLabel(widget)
        self.a_lbl.setObjectName("a_lbl")
        self.gridLayout_2.addWidget(self.a_lbl, 0, 0, 1, 1)
        self.a_le = QtWidgets.QLineEdit(widget)
        self.a_le.setMinimumSize(QtCore.QSize(155, 20))
        self.a_le.setObjectName("a_le")
        self.gridLayout_2.addWidget(self.a_le, 0, 1, 1, 1)
        self.h_lbl = QtWidgets.QLabel(widget)
        self.h_lbl.setObjectName("h_lbl")
        self.gridLayout_2.addWidget(self.h_lbl, 1, 0, 1, 1)
        self.h_le = QtWidgets.QLineEdit(widget)
        self.h_le.setMinimumSize(QtCore.QSize(155, 20))
        self.h_le.setObjectName("h_le")
        self.gridLayout_2.addWidget(self.h_le, 1, 1, 1, 1)
        self.n_lbl = QtWidgets.QLabel(widget)
        self.n_lbl.setObjectName("n_lbl")
        self.gridLayout_2.addWidget(self.n_lbl, 2, 0, 1, 1)
        self.n_le = QtWidgets.QLineEdit(widget)
        self.n_le.setMinimumSize(QtCore.QSize(155, 20))
        self.n_le.setObjectName("n_le")
        self.gridLayout_2.addWidget(self.n_le, 2, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(13, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.step_lbl = QtWidgets.QLabel(widget)
        self.step_lbl.setObjectName("step_lbl")
        self.gridLayout.addWidget(self.step_lbl, 1, 0, 1, 1)
        self.stop_le = QtWidgets.QLineEdit(widget)
        self.stop_le.setMinimumSize(QtCore.QSize(155, 20))
        self.stop_le.setObjectName("stop_le")
        self.gridLayout.addWidget(self.stop_le, 2, 1, 1, 1)
        self.start_le = QtWidgets.QLineEdit(widget)
        self.start_le.setMinimumSize(QtCore.QSize(155, 20))
        self.start_le.setObjectName("start_le")
        self.gridLayout.addWidget(self.start_le, 0, 1, 1, 1)
        self.step_le = QtWidgets.QLineEdit(widget)
        self.step_le.setMinimumSize(QtCore.QSize(155, 20))
        self.step_le.setObjectName("step_le")
        self.gridLayout.addWidget(self.step_le, 1, 1, 1, 1)
        self.stop_lbl = QtWidgets.QLabel(widget)
        self.stop_lbl.setObjectName("stop_lbl")
        self.gridLayout.addWidget(self.stop_lbl, 2, 0, 1, 1)
        self.start_lbl = QtWidgets.QLabel(widget)
        self.start_lbl.setObjectName("start_lbl")
        self.gridLayout.addWidget(self.start_lbl, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.title_2 = QtWidgets.QLabel(widget)
        self.title_2.setObjectName("title_2")
        self.gridLayout_3.addWidget(self.title_2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        self.va_pw = PlotWidget(widget)
        self.va_pw.setObjectName("va_pw")
        self.gridLayout_5.addWidget(self.va_pw, 1, 0, 1, 3)
        self.calc_btn = QtWidgets.QPushButton(widget)
        self.calc_btn.setObjectName("calc_btn")
        self.gridLayout_5.addWidget(self.calc_btn, 2, 0, 1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.table_tw = QtWidgets.QTableWidget(widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_tw.sizePolicy().hasHeightForWidth())
        self.table_tw.setSizePolicy(sizePolicy)
        self.table_tw.setMinimumSize(QtCore.QSize(201, 0))
        self.table_tw.setObjectName("table_tw")
        self.table_tw.setColumnCount(0)
        self.table_tw.setRowCount(0)
        self.gridLayout_6.addWidget(self.table_tw, 0, 1, 1, 1)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Simulation of the volt-ampere characteristic of a Josephson junction"))
        self.title_1.setText(_translate("widget", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">equation and numerical method:</span></p></body></html>"))
        self.a_lbl.setText(_translate("widget", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-style:italic;\">a =</span></p></body></html>"))
        self.h_lbl.setText(_translate("widget", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-style:italic;\">h =</span></p></body></html>"))
        self.n_lbl.setText(_translate("widget", "<html><head/><body><p align=\"right\"><span style=\" font-size:14pt; font-style:italic;\">N =</span></p></body></html>"))
        self.step_lbl.setText(_translate("widget", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">step =</span></p></body></html>"))
        self.stop_lbl.setText(_translate("widget", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">stop =</span></p></body></html>"))
        self.start_lbl.setText(_translate("widget", "<html><head/><body><p><span style=\" font-size:14pt; font-style:italic;\">start =</span></p></body></html>"))
        self.title_2.setText(_translate("widget", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">j axis:</span></p></body></html>"))
        self.calc_btn.setText(_translate("widget", "Calculate"))

from pyqtgraph import PlotWidget
